description: |
  Drupal Stand CI. Please select the version of DrupalStand to use.
  Any available tag from this list can be used: https://hub.docker.com/r/mobomo/drupalstand-ci/tags
docker:
  - image: 'mobomo/drupalstand-ci:<< parameters.tag >>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific mobomo/drupalstand-ci image variant:
      https://hub.docker.com/r/mobomo/drupalstand-ci/tags
    type: string
